#
# linux/drivers/mtd/devices/rtd2885/Makefile
#
# $Id: Makefile,v 1.1.1.1 2013/03/19 08:37:22 rtlac Exp $

EXTRA_CFLAGS += -DSPI_KERNEL

obj-y	+= spi_probe.o spi_cmd.o spi_common.o spi_flash.o
CFLAGS_spi_probe.o += -O0
CFLAGS_spi_cmd.o += -O0
CFLAGS_spi_common.o += -O0
CFLAGS_spi_flash.o += -O0
