#!/bin/sh

hostname rlx-linux

echo "mounting proc ..."
mount -t proc proc /proc
mount -t ramfs ramfs /var

echo "mking dirs ..."
mkdir /var/tmp
mkdir /var/log
mkdir /var/run
mkdir /var/lock
cat /etc/motd

# init bridge
mac0="00e04c"`cat /dev/urandom | tr -dc "a-f0-9" | fold -w 6 | head -n 1`
mac1="00e04c"`cat /dev/urandom | tr -dc "a-f0-9" | fold -w 6 | head -n 1`

ifconfig eth0 hw ether "$mac0"
ifconfig eth1 hw ether "$mac1"

brctl addbr br0
brctl addif br0 eth0
brctl addif br0 eth1
ifconfig br0 192.168.1.254

ifconfig eth0 up
ifconfig eth1 up
ifconfig lo up
