#!/bin/sh

hostname rlx-linux

echo "mounting proc ..."
mount -t proc proc /proc
mount -t ramfs ramfs /var

echo "mking dirs ..."
mkdir /var/tmp
mkdir /var/log
mkdir /var/run
mkdir /var/lock
cat /etc/motd

hcd -daemon

